export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'

export const REPORTE_REQUEST = 'REPORTE_REQUEST'
export const REPORTE_SUCCESS = 'REPORTE_SUCCESS'
export const REPORTE_FAILURE = 'REPORTE_FAILURE' 